# Generated by Django 5.1.6 on 2025-02-23 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_conversation_title_alter_message_conversation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='title',
        ),
    ]
